name: Build
on:
    push:
        branches: [master]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            packages: write    
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13'
                cache: 'pip'
            - name: Install dependecies
              run: pip install -c constraints.txt .[dev]
            # - name: Static analysis
            #    run: pre-commit run --all-files
            - name: Unit tests
              run: pytest -v test/unit
            - name: Create Docker image
              run: docker build -t employee-python .
            # - name: Log in to the Container registry
            #   uses: docker/login-action@v3
            #   with:
            #     registry: ghcr.io
            #     username: ${{ github.actor }}
            #     password: ${{ secrets.GITHUB_TOKEN }}
            # - name: Generate Docker image metadata
            #   id: meta
            #   uses: docker/metadata-action@v5
            #   with:
            #     images: ghcr.io/${{ github.repository }}    
            # - name: Build and push Docker image
            #   uses: docker/build-push-action@v4
            #   with:
            #     context: .
            #     push: true
            #     tags: ${{ steps.meta.outputs.tags }}
            - name: Build static files
              run: mkdocs build
            - name: Upload static files as artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: site/

    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
                            
                        